### PR TITLE
grid data cells are only updated when cityIO data has changed

### PR DESCRIPTION
**Pull request by aberke**

### CODE REVIEW

**Comment by aberke** [comment]
Addresses issue: https://github.com/CityScope/CSL_Hamburg_Grasbrook_Angular_Prototype/issues/12

**Comment by RELNO** [comment]
Thanks -- it appears that every grid scale [ncol,nrows] other than the 12,36 breaks the app:

Screen Shot 2019-03-14 at 15 47 32

**Comment by aberke** [comment]
Can you provide information on how to reproduce the error?

**Comment by RELNO** [comment]
Reproduction:

Change  https://github.com/CityScope/CSL_Hamburg_Grasbrook_Angular_Prototype/blob/master/src/assets/mock-grid-data.json `nrows` or `ncols` to anything else than the baseline values.

**Comment by aberke** [comment]
I just spent some time doing just that and I couldn't reproduce the issue.  Can you provide the nrows,ncols values that were problematic for you?

**Comment by RELNO** [comment]
Screen Shot 2019-03-14 at 16 41 53

not sure what the rule here, but looks like below 12,36 is where it's mostly happening

**Comment by aberke** [comment]
That's because you then have an invalid grid array with more items than there should be.  I can add in a check for bad data but... that's a data quality problem?

**Comment by aberke** [comment]
I pushed a commit to prevent that error caused by bad data.

**Comment by RELNO** [comment]
what does 'an invalid grid array with more items than there should be' mean?
A grid should be created for any nrow*ncol

**Comment by aberke** [comment]
I would expect a grid with nrows and ncols to have nrows*ncols indices, no?

**Comment by RELNO** [comment]
I'm again not sure I understand...  

- The size of the grid is simply set by two numbers defined in the json retrieved from cityIO [or any other source]. 
- This represents the physical grid dimensions.
- Expected behavior is that when one of these numbers change, a new matrix is created

Expected behavior is that no matter what ncols or nrows are, a grid will be created.

**Pull request merged**
